package clientEnum;

public enum Event {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    OPEN_CHAT_WIDGET,
    OPEN_ADD_FRIEND,
    OPEN_CREATE_GROUP,
    OPEN_JOIN_GROUP,
    OPEN_FACE_WIDGET,
    MESSAGE_ARRIVE,
    USERLIST_CHANGE,
    SEND_MESSAGE,
    OPEN_REQUEST_MANAGEMENT,
    UPDATE_FRIEND_LIST;
}
